---
- hosts: all
  roles:
    - role: datadog.datadog
      become: yes
    - role: redmine_server
  tasks:
    - name: install pip
      become: yes
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: install docker-dependency
      pip:
        name: docker