- hosts: all
  become: yes
  tasks:
    - name: install pip
      become: yes
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: install docker-dependency
      pip:
        name: docker

    - name: start container
      community.docker.docker_container:
        name: redmine-example-app
        image: redmine
        ports:
          - "8080:3000"