---
- hosts: all
  become: yes
  roles:
    - datadog.datadog
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.com"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: application health check status
            url: http://localhost:8080
            timeout: 5
            method: GET
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: install docker-dependency
      pip:
        name: docker

    - name: start container
      docker_container:
        name: redmine-example-app
        image: redmine
        ports:
          - "8080:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ postgres_host }}"
          REDMINE_DB_PORT: "{{ postgres_port }}"
          REDMINE_DB_USERNAME: "{{ postgres_user }}"
          REDMINE_DB_PASSWORD: "{{ postgres_pass }}"
          REDMINE_DB_DATABASE: "{{ postgres_db }}"